# Generated by Django 5.0.4 on 2024-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
